spring:
  application:
    name: cambio

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  docker:
    compose:
      enabled: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  github:
    app:
      id: ${GITHUB_APP_ID}
      installationId: ${GITHUB_INSTALLATION_ID}
      privateKey: ${GITHUB_PRIVATE_KEY}
      owner: ${GITHUB_OWNER}
      repo: ${GITHUB_REPO}

server:
  address: 0.0.0.0
  port: 8080


